FROM bellsoft/liberica-openjdk-alpine:19
COPY ./java ./copy_src
RUN mkdir ./out
RUN javac -sourcepath ./copy_src -d out copy_src/ru/jucharick/lesson1/sample/Main.java
CMD java -classpath ./out ru.jucharick.lesson1.sample.Main