FROM bellsoft/liberica-openjdk-alpine:19
COPY ./java ./tosrc
RUN mkdir ./out
RUN javac -sourcepath ./src -d out src/ru/geekbrains/lesson1/sample/Main.java
CMD java -classpath ./out ru.geekbrains.lesson1.sample.Main